trustPolicy: no-downgrade
trustPolicyExclude:
  - 'chokidar'

strictDepBuilds: true
allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: true
  prisma: true
  protobufjs: true
  msw: true
  sharp: true
