export const FREE_PLAN_MAX_AI_SEARCHES = 3
export const MAX_PROMPT_LENGTH = 300
export const MAX_AI_SEARCH_RESULTS = 20
export const DAILY_GLOBAL_AI_SEARCH_CAP = 500
export const AI_SEARCH_TIMEOUT_MS = 15_000
