/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as SitemapMemesDotxmlRouteImport } from './routes/sitemap-memes[.]xml'
import { Route as SitemapCategoriesDotxmlRouteImport } from './routes/sitemap-categories[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as HealthRouteImport } from './routes/health'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as Public__rootRouteRouteImport } from './routes/_public__root/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Public__rootIndexRouteImport } from './routes/_public__root/index'
import { Route as ApiSentryTunnelRouteImport } from './routes/api/sentry-tunnel'
import { Route as ApiBunnyRouteImport } from './routes/api/bunny'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminDownloaderRouteImport } from './routes/admin/downloader'
import { Route as Public__rootDefaultRouteRouteImport } from './routes/_public__root/_default/route'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSubmissionsIndexRouteImport } from './routes/admin/submissions/index'
import { Route as AdminLibraryIndexRouteImport } from './routes/admin/library/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as ApiCronVerificationReminderRouteImport } from './routes/api/cron/verification-reminder'
import { Route as ApiCronSyncBunnyTitlesRouteImport } from './routes/api/cron/sync-bunny-titles'
import { Route as ApiCronSyncAlgoliaRouteImport } from './routes/api/cron/sync-algolia'
import { Route as ApiCronCleanupRouteImport } from './routes/api/cron/cleanup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminLibraryMemeIdRouteImport } from './routes/admin/library/$memeId'
import { Route as Public__rootDefaultTermsOfUseRouteImport } from './routes/_public__root/_default/terms-of-use'
import { Route as Public__rootDefaultPrivacyRouteImport } from './routes/_public__root/_default/privacy'
import { Route as Public__rootDefaultMentionsLegalesRouteImport } from './routes/_public__root/_default/mentions-legales'
import { Route as Public__rootDefaultFavoritesRouteImport } from './routes/_public__root/_default/favorites'
import { Route as Public__rootDefaultDmcaRouteImport } from './routes/_public__root/_default/dmca'
import { Route as Public__rootDefaultSettingsRouteRouteImport } from './routes/_public__root/_default/settings/route'
import { Route as Public__rootDefaultSubmitIndexRouteImport } from './routes/_public__root/_default/submit/index'
import { Route as Public__rootDefaultSettingsIndexRouteImport } from './routes/_public__root/_default/settings/index'
import { Route as Public__rootDefaultRandomIndexRouteImport } from './routes/_public__root/_default/random/index'
import { Route as Public__rootDefaultPricingIndexRouteImport } from './routes/_public__root/_default/pricing/index'
import { Route as Public__rootDefaultMemesIndexRouteImport } from './routes/_public__root/_default/memes/index'
import { Route as StudioMemesMemeIdStudioRouteImport } from './routes/_studio/memes.$memeId.studio'
import { Route as Public__rootDefaultPasswordResetRouteImport } from './routes/_public__root/_default/password.reset'
import { Route as Public__rootDefaultPasswordCreateNewRouteImport } from './routes/_public__root/_default/password.create-new'
import { Route as Public__rootDefaultMemesMemeIdRouteImport } from './routes/_public__root/_default/memes/$memeId'
import { Route as Public__rootDefaultCheckoutSuccessRouteImport } from './routes/_public__root/_default/checkout.success'
import { Route as Public__rootDefaultMemesCategorySlugRouteImport } from './routes/_public__root/_default/memes/category/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapMemesDotxmlRoute = SitemapMemesDotxmlRouteImport.update({
  id: '/sitemap-memes.xml',
  path: '/sitemap-memes.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCategoriesDotxmlRoute = SitemapCategoriesDotxmlRouteImport.update({
  id: '/sitemap-categories.xml',
  path: '/sitemap-categories.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Public__rootRouteRoute = Public__rootRouteRouteImport.update({
  id: '/_public__root',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Public__rootIndexRoute = Public__rootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Public__rootRouteRoute,
} as any)
const ApiSentryTunnelRoute = ApiSentryTunnelRouteImport.update({
  id: '/api/sentry-tunnel',
  path: '/api/sentry-tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBunnyRoute = ApiBunnyRouteImport.update({
  id: '/api/bunny',
  path: '/api/bunny',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDownloaderRoute = AdminDownloaderRouteImport.update({
  id: '/downloader',
  path: '/downloader',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Public__rootDefaultRouteRoute =
  Public__rootDefaultRouteRouteImport.update({
    id: '/_default',
    getParentRoute: () => Public__rootRouteRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsIndexRoute = AdminSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLibraryIndexRoute = AdminLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiCronVerificationReminderRoute =
  ApiCronVerificationReminderRouteImport.update({
    id: '/api/cron/verification-reminder',
    path: '/api/cron/verification-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronSyncBunnyTitlesRoute = ApiCronSyncBunnyTitlesRouteImport.update({
  id: '/api/cron/sync-bunny-titles',
  path: '/api/cron/sync-bunny-titles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncAlgoliaRoute = ApiCronSyncAlgoliaRouteImport.update({
  id: '/api/cron/sync-algolia',
  path: '/api/cron/sync-algolia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCleanupRoute = ApiCronCleanupRouteImport.update({
  id: '/api/cron/cleanup',
  path: '/api/cron/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLibraryMemeIdRoute = AdminLibraryMemeIdRouteImport.update({
  id: '/library/$memeId',
  path: '/library/$memeId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Public__rootDefaultTermsOfUseRoute =
  Public__rootDefaultTermsOfUseRouteImport.update({
    id: '/terms-of-use',
    path: '/terms-of-use',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultPrivacyRoute =
  Public__rootDefaultPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultMentionsLegalesRoute =
  Public__rootDefaultMentionsLegalesRouteImport.update({
    id: '/mentions-legales',
    path: '/mentions-legales',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultFavoritesRoute =
  Public__rootDefaultFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultDmcaRoute = Public__rootDefaultDmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => Public__rootDefaultRouteRoute,
} as any)
const Public__rootDefaultSettingsRouteRoute =
  Public__rootDefaultSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultSubmitIndexRoute =
  Public__rootDefaultSubmitIndexRouteImport.update({
    id: '/submit/',
    path: '/submit/',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultSettingsIndexRoute =
  Public__rootDefaultSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Public__rootDefaultSettingsRouteRoute,
  } as any)
const Public__rootDefaultRandomIndexRoute =
  Public__rootDefaultRandomIndexRouteImport.update({
    id: '/random/',
    path: '/random/',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultPricingIndexRoute =
  Public__rootDefaultPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultMemesIndexRoute =
  Public__rootDefaultMemesIndexRouteImport.update({
    id: '/memes/',
    path: '/memes/',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const StudioMemesMemeIdStudioRoute = StudioMemesMemeIdStudioRouteImport.update({
  id: '/memes/$memeId/studio',
  path: '/memes/$memeId/studio',
  getParentRoute: () => StudioRoute,
} as any)
const Public__rootDefaultPasswordResetRoute =
  Public__rootDefaultPasswordResetRouteImport.update({
    id: '/password/reset',
    path: '/password/reset',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultPasswordCreateNewRoute =
  Public__rootDefaultPasswordCreateNewRouteImport.update({
    id: '/password/create-new',
    path: '/password/create-new',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultMemesMemeIdRoute =
  Public__rootDefaultMemesMemeIdRouteImport.update({
    id: '/memes/$memeId',
    path: '/memes/$memeId',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultCheckoutSuccessRoute =
  Public__rootDefaultCheckoutSuccessRouteImport.update({
    id: '/checkout/success',
    path: '/checkout/success',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)
const Public__rootDefaultMemesCategorySlugRoute =
  Public__rootDefaultMemesCategorySlugRouteImport.update({
    id: '/memes/category/$slug',
    path: '/memes/category/$slug',
    getParentRoute: () => Public__rootDefaultRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof Public__rootIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/reels': typeof ReelsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-memes.xml': typeof SitemapMemesDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/downloader': typeof AdminDownloaderRoute
  '/admin/services': typeof AdminServicesRoute
  '/api/bunny': typeof ApiBunnyRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/admin/': typeof AdminIndexRoute
  '/settings': typeof Public__rootDefaultSettingsRouteRouteWithChildren
  '/dmca': typeof Public__rootDefaultDmcaRoute
  '/favorites': typeof Public__rootDefaultFavoritesRoute
  '/mentions-legales': typeof Public__rootDefaultMentionsLegalesRoute
  '/privacy': typeof Public__rootDefaultPrivacyRoute
  '/terms-of-use': typeof Public__rootDefaultTermsOfUseRoute
  '/admin/library/$memeId': typeof AdminLibraryMemeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/cleanup': typeof ApiCronCleanupRoute
  '/api/cron/sync-algolia': typeof ApiCronSyncAlgoliaRoute
  '/api/cron/sync-bunny-titles': typeof ApiCronSyncBunnyTitlesRoute
  '/api/cron/verification-reminder': typeof ApiCronVerificationReminderRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/library/': typeof AdminLibraryIndexRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/checkout/success': typeof Public__rootDefaultCheckoutSuccessRoute
  '/memes/$memeId': typeof Public__rootDefaultMemesMemeIdRoute
  '/password/create-new': typeof Public__rootDefaultPasswordCreateNewRoute
  '/password/reset': typeof Public__rootDefaultPasswordResetRoute
  '/memes/$memeId/studio': typeof StudioMemesMemeIdStudioRoute
  '/memes/': typeof Public__rootDefaultMemesIndexRoute
  '/pricing/': typeof Public__rootDefaultPricingIndexRoute
  '/random/': typeof Public__rootDefaultRandomIndexRoute
  '/settings/': typeof Public__rootDefaultSettingsIndexRoute
  '/submit/': typeof Public__rootDefaultSubmitIndexRoute
  '/memes/category/$slug': typeof Public__rootDefaultMemesCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof Public__rootIndexRoute
  '/health': typeof HealthRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/reels': typeof ReelsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-memes.xml': typeof SitemapMemesDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/downloader': typeof AdminDownloaderRoute
  '/admin/services': typeof AdminServicesRoute
  '/api/bunny': typeof ApiBunnyRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/admin': typeof AdminIndexRoute
  '/dmca': typeof Public__rootDefaultDmcaRoute
  '/favorites': typeof Public__rootDefaultFavoritesRoute
  '/mentions-legales': typeof Public__rootDefaultMentionsLegalesRoute
  '/privacy': typeof Public__rootDefaultPrivacyRoute
  '/terms-of-use': typeof Public__rootDefaultTermsOfUseRoute
  '/admin/library/$memeId': typeof AdminLibraryMemeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/cleanup': typeof ApiCronCleanupRoute
  '/api/cron/sync-algolia': typeof ApiCronSyncAlgoliaRoute
  '/api/cron/sync-bunny-titles': typeof ApiCronSyncBunnyTitlesRoute
  '/api/cron/verification-reminder': typeof ApiCronVerificationReminderRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/library': typeof AdminLibraryIndexRoute
  '/admin/submissions': typeof AdminSubmissionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/checkout/success': typeof Public__rootDefaultCheckoutSuccessRoute
  '/memes/$memeId': typeof Public__rootDefaultMemesMemeIdRoute
  '/password/create-new': typeof Public__rootDefaultPasswordCreateNewRoute
  '/password/reset': typeof Public__rootDefaultPasswordResetRoute
  '/memes/$memeId/studio': typeof StudioMemesMemeIdStudioRoute
  '/memes': typeof Public__rootDefaultMemesIndexRoute
  '/pricing': typeof Public__rootDefaultPricingIndexRoute
  '/random': typeof Public__rootDefaultRandomIndexRoute
  '/settings': typeof Public__rootDefaultSettingsIndexRoute
  '/submit': typeof Public__rootDefaultSubmitIndexRoute
  '/memes/category/$slug': typeof Public__rootDefaultMemesCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public__root': typeof Public__rootRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_studio': typeof StudioRouteWithChildren
  '/health': typeof HealthRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/reels': typeof ReelsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-memes.xml': typeof SitemapMemesDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public__root/_default': typeof Public__rootDefaultRouteRouteWithChildren
  '/admin/downloader': typeof AdminDownloaderRoute
  '/admin/services': typeof AdminServicesRoute
  '/api/bunny': typeof ApiBunnyRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/_public__root/': typeof Public__rootIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public__root/_default/settings': typeof Public__rootDefaultSettingsRouteRouteWithChildren
  '/_public__root/_default/dmca': typeof Public__rootDefaultDmcaRoute
  '/_public__root/_default/favorites': typeof Public__rootDefaultFavoritesRoute
  '/_public__root/_default/mentions-legales': typeof Public__rootDefaultMentionsLegalesRoute
  '/_public__root/_default/privacy': typeof Public__rootDefaultPrivacyRoute
  '/_public__root/_default/terms-of-use': typeof Public__rootDefaultTermsOfUseRoute
  '/admin/library/$memeId': typeof AdminLibraryMemeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/cleanup': typeof ApiCronCleanupRoute
  '/api/cron/sync-algolia': typeof ApiCronSyncAlgoliaRoute
  '/api/cron/sync-bunny-titles': typeof ApiCronSyncBunnyTitlesRoute
  '/api/cron/verification-reminder': typeof ApiCronVerificationReminderRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/library/': typeof AdminLibraryIndexRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_public__root/_default/checkout/success': typeof Public__rootDefaultCheckoutSuccessRoute
  '/_public__root/_default/memes/$memeId': typeof Public__rootDefaultMemesMemeIdRoute
  '/_public__root/_default/password/create-new': typeof Public__rootDefaultPasswordCreateNewRoute
  '/_public__root/_default/password/reset': typeof Public__rootDefaultPasswordResetRoute
  '/_studio/memes/$memeId/studio': typeof StudioMemesMemeIdStudioRoute
  '/_public__root/_default/memes/': typeof Public__rootDefaultMemesIndexRoute
  '/_public__root/_default/pricing/': typeof Public__rootDefaultPricingIndexRoute
  '/_public__root/_default/random/': typeof Public__rootDefaultRandomIndexRoute
  '/_public__root/_default/settings/': typeof Public__rootDefaultSettingsIndexRoute
  '/_public__root/_default/submit/': typeof Public__rootDefaultSubmitIndexRoute
  '/_public__root/_default/memes/category/$slug': typeof Public__rootDefaultMemesCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/health'
    | '/manifest.json'
    | '/reels'
    | '/robots.txt'
    | '/sitemap-categories.xml'
    | '/sitemap-memes.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/admin/downloader'
    | '/admin/services'
    | '/api/bunny'
    | '/api/sentry-tunnel'
    | '/admin/'
    | '/settings'
    | '/dmca'
    | '/favorites'
    | '/mentions-legales'
    | '/privacy'
    | '/terms-of-use'
    | '/admin/library/$memeId'
    | '/api/auth/$'
    | '/api/cron/cleanup'
    | '/api/cron/sync-algolia'
    | '/api/cron/sync-bunny-titles'
    | '/api/cron/verification-reminder'
    | '/admin/categories/'
    | '/admin/library/'
    | '/admin/submissions/'
    | '/admin/users/'
    | '/checkout/success'
    | '/memes/$memeId'
    | '/password/create-new'
    | '/password/reset'
    | '/memes/$memeId/studio'
    | '/memes/'
    | '/pricing/'
    | '/random/'
    | '/settings/'
    | '/submit/'
    | '/memes/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/manifest.json'
    | '/reels'
    | '/robots.txt'
    | '/sitemap-categories.xml'
    | '/sitemap-memes.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/admin/downloader'
    | '/admin/services'
    | '/api/bunny'
    | '/api/sentry-tunnel'
    | '/admin'
    | '/dmca'
    | '/favorites'
    | '/mentions-legales'
    | '/privacy'
    | '/terms-of-use'
    | '/admin/library/$memeId'
    | '/api/auth/$'
    | '/api/cron/cleanup'
    | '/api/cron/sync-algolia'
    | '/api/cron/sync-bunny-titles'
    | '/api/cron/verification-reminder'
    | '/admin/categories'
    | '/admin/library'
    | '/admin/submissions'
    | '/admin/users'
    | '/checkout/success'
    | '/memes/$memeId'
    | '/password/create-new'
    | '/password/reset'
    | '/memes/$memeId/studio'
    | '/memes'
    | '/pricing'
    | '/random'
    | '/settings'
    | '/submit'
    | '/memes/category/$slug'
  id:
    | '__root__'
    | '/_public__root'
    | '/admin'
    | '/_studio'
    | '/health'
    | '/manifest.json'
    | '/reels'
    | '/robots.txt'
    | '/sitemap-categories.xml'
    | '/sitemap-memes.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/_public__root/_default'
    | '/admin/downloader'
    | '/admin/services'
    | '/api/bunny'
    | '/api/sentry-tunnel'
    | '/_public__root/'
    | '/admin/'
    | '/_public__root/_default/settings'
    | '/_public__root/_default/dmca'
    | '/_public__root/_default/favorites'
    | '/_public__root/_default/mentions-legales'
    | '/_public__root/_default/privacy'
    | '/_public__root/_default/terms-of-use'
    | '/admin/library/$memeId'
    | '/api/auth/$'
    | '/api/cron/cleanup'
    | '/api/cron/sync-algolia'
    | '/api/cron/sync-bunny-titles'
    | '/api/cron/verification-reminder'
    | '/admin/categories/'
    | '/admin/library/'
    | '/admin/submissions/'
    | '/admin/users/'
    | '/_public__root/_default/checkout/success'
    | '/_public__root/_default/memes/$memeId'
    | '/_public__root/_default/password/create-new'
    | '/_public__root/_default/password/reset'
    | '/_studio/memes/$memeId/studio'
    | '/_public__root/_default/memes/'
    | '/_public__root/_default/pricing/'
    | '/_public__root/_default/random/'
    | '/_public__root/_default/settings/'
    | '/_public__root/_default/submit/'
    | '/_public__root/_default/memes/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Public__rootRouteRoute: typeof Public__rootRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
  HealthRoute: typeof HealthRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  ReelsRoute: typeof ReelsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapCategoriesDotxmlRoute: typeof SitemapCategoriesDotxmlRoute
  SitemapMemesDotxmlRoute: typeof SitemapMemesDotxmlRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBunnyRoute: typeof ApiBunnyRoute
  ApiSentryTunnelRoute: typeof ApiSentryTunnelRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronCleanupRoute: typeof ApiCronCleanupRoute
  ApiCronSyncAlgoliaRoute: typeof ApiCronSyncAlgoliaRoute
  ApiCronSyncBunnyTitlesRoute: typeof ApiCronSyncBunnyTitlesRoute
  ApiCronVerificationReminderRoute: typeof ApiCronVerificationReminderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-memes.xml': {
      id: '/sitemap-memes.xml'
      path: '/sitemap-memes.xml'
      fullPath: '/sitemap-memes.xml'
      preLoaderRoute: typeof SitemapMemesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-categories.xml': {
      id: '/sitemap-categories.xml'
      path: '/sitemap-categories.xml'
      fullPath: '/sitemap-categories.xml'
      preLoaderRoute: typeof SitemapCategoriesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public__root': {
      id: '/_public__root'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Public__rootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public__root/': {
      id: '/_public__root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Public__rootIndexRouteImport
      parentRoute: typeof Public__rootRouteRoute
    }
    '/api/sentry-tunnel': {
      id: '/api/sentry-tunnel'
      path: '/api/sentry-tunnel'
      fullPath: '/api/sentry-tunnel'
      preLoaderRoute: typeof ApiSentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bunny': {
      id: '/api/bunny'
      path: '/api/bunny'
      fullPath: '/api/bunny'
      preLoaderRoute: typeof ApiBunnyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/downloader': {
      id: '/admin/downloader'
      path: '/downloader'
      fullPath: '/admin/downloader'
      preLoaderRoute: typeof AdminDownloaderRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public__root/_default': {
      id: '/_public__root/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Public__rootDefaultRouteRouteImport
      parentRoute: typeof Public__rootRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions/': {
      id: '/admin/submissions/'
      path: '/submissions'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof AdminSubmissionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/library/': {
      id: '/admin/library/'
      path: '/library'
      fullPath: '/admin/library/'
      preLoaderRoute: typeof AdminLibraryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/cron/verification-reminder': {
      id: '/api/cron/verification-reminder'
      path: '/api/cron/verification-reminder'
      fullPath: '/api/cron/verification-reminder'
      preLoaderRoute: typeof ApiCronVerificationReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-bunny-titles': {
      id: '/api/cron/sync-bunny-titles'
      path: '/api/cron/sync-bunny-titles'
      fullPath: '/api/cron/sync-bunny-titles'
      preLoaderRoute: typeof ApiCronSyncBunnyTitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-algolia': {
      id: '/api/cron/sync-algolia'
      path: '/api/cron/sync-algolia'
      fullPath: '/api/cron/sync-algolia'
      preLoaderRoute: typeof ApiCronSyncAlgoliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cleanup': {
      id: '/api/cron/cleanup'
      path: '/api/cron/cleanup'
      fullPath: '/api/cron/cleanup'
      preLoaderRoute: typeof ApiCronCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/library/$memeId': {
      id: '/admin/library/$memeId'
      path: '/library/$memeId'
      fullPath: '/admin/library/$memeId'
      preLoaderRoute: typeof AdminLibraryMemeIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public__root/_default/terms-of-use': {
      id: '/_public__root/_default/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof Public__rootDefaultTermsOfUseRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/privacy': {
      id: '/_public__root/_default/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof Public__rootDefaultPrivacyRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/mentions-legales': {
      id: '/_public__root/_default/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof Public__rootDefaultMentionsLegalesRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/favorites': {
      id: '/_public__root/_default/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof Public__rootDefaultFavoritesRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/dmca': {
      id: '/_public__root/_default/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof Public__rootDefaultDmcaRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/settings': {
      id: '/_public__root/_default/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof Public__rootDefaultSettingsRouteRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/submit/': {
      id: '/_public__root/_default/submit/'
      path: '/submit'
      fullPath: '/submit/'
      preLoaderRoute: typeof Public__rootDefaultSubmitIndexRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/settings/': {
      id: '/_public__root/_default/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof Public__rootDefaultSettingsIndexRouteImport
      parentRoute: typeof Public__rootDefaultSettingsRouteRoute
    }
    '/_public__root/_default/random/': {
      id: '/_public__root/_default/random/'
      path: '/random'
      fullPath: '/random/'
      preLoaderRoute: typeof Public__rootDefaultRandomIndexRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/pricing/': {
      id: '/_public__root/_default/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof Public__rootDefaultPricingIndexRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/memes/': {
      id: '/_public__root/_default/memes/'
      path: '/memes'
      fullPath: '/memes/'
      preLoaderRoute: typeof Public__rootDefaultMemesIndexRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_studio/memes/$memeId/studio': {
      id: '/_studio/memes/$memeId/studio'
      path: '/memes/$memeId/studio'
      fullPath: '/memes/$memeId/studio'
      preLoaderRoute: typeof StudioMemesMemeIdStudioRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_public__root/_default/password/reset': {
      id: '/_public__root/_default/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof Public__rootDefaultPasswordResetRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/password/create-new': {
      id: '/_public__root/_default/password/create-new'
      path: '/password/create-new'
      fullPath: '/password/create-new'
      preLoaderRoute: typeof Public__rootDefaultPasswordCreateNewRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/memes/$memeId': {
      id: '/_public__root/_default/memes/$memeId'
      path: '/memes/$memeId'
      fullPath: '/memes/$memeId'
      preLoaderRoute: typeof Public__rootDefaultMemesMemeIdRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/checkout/success': {
      id: '/_public__root/_default/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof Public__rootDefaultCheckoutSuccessRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
    '/_public__root/_default/memes/category/$slug': {
      id: '/_public__root/_default/memes/category/$slug'
      path: '/memes/category/$slug'
      fullPath: '/memes/category/$slug'
      preLoaderRoute: typeof Public__rootDefaultMemesCategorySlugRouteImport
      parentRoute: typeof Public__rootDefaultRouteRoute
    }
  }
}

interface Public__rootDefaultSettingsRouteRouteChildren {
  Public__rootDefaultSettingsIndexRoute: typeof Public__rootDefaultSettingsIndexRoute
}

const Public__rootDefaultSettingsRouteRouteChildren: Public__rootDefaultSettingsRouteRouteChildren =
  {
    Public__rootDefaultSettingsIndexRoute:
      Public__rootDefaultSettingsIndexRoute,
  }

const Public__rootDefaultSettingsRouteRouteWithChildren =
  Public__rootDefaultSettingsRouteRoute._addFileChildren(
    Public__rootDefaultSettingsRouteRouteChildren,
  )

interface Public__rootDefaultRouteRouteChildren {
  Public__rootDefaultSettingsRouteRoute: typeof Public__rootDefaultSettingsRouteRouteWithChildren
  Public__rootDefaultDmcaRoute: typeof Public__rootDefaultDmcaRoute
  Public__rootDefaultFavoritesRoute: typeof Public__rootDefaultFavoritesRoute
  Public__rootDefaultMentionsLegalesRoute: typeof Public__rootDefaultMentionsLegalesRoute
  Public__rootDefaultPrivacyRoute: typeof Public__rootDefaultPrivacyRoute
  Public__rootDefaultTermsOfUseRoute: typeof Public__rootDefaultTermsOfUseRoute
  Public__rootDefaultCheckoutSuccessRoute: typeof Public__rootDefaultCheckoutSuccessRoute
  Public__rootDefaultMemesMemeIdRoute: typeof Public__rootDefaultMemesMemeIdRoute
  Public__rootDefaultPasswordCreateNewRoute: typeof Public__rootDefaultPasswordCreateNewRoute
  Public__rootDefaultPasswordResetRoute: typeof Public__rootDefaultPasswordResetRoute
  Public__rootDefaultMemesIndexRoute: typeof Public__rootDefaultMemesIndexRoute
  Public__rootDefaultPricingIndexRoute: typeof Public__rootDefaultPricingIndexRoute
  Public__rootDefaultRandomIndexRoute: typeof Public__rootDefaultRandomIndexRoute
  Public__rootDefaultSubmitIndexRoute: typeof Public__rootDefaultSubmitIndexRoute
  Public__rootDefaultMemesCategorySlugRoute: typeof Public__rootDefaultMemesCategorySlugRoute
}

const Public__rootDefaultRouteRouteChildren: Public__rootDefaultRouteRouteChildren =
  {
    Public__rootDefaultSettingsRouteRoute:
      Public__rootDefaultSettingsRouteRouteWithChildren,
    Public__rootDefaultDmcaRoute: Public__rootDefaultDmcaRoute,
    Public__rootDefaultFavoritesRoute: Public__rootDefaultFavoritesRoute,
    Public__rootDefaultMentionsLegalesRoute:
      Public__rootDefaultMentionsLegalesRoute,
    Public__rootDefaultPrivacyRoute: Public__rootDefaultPrivacyRoute,
    Public__rootDefaultTermsOfUseRoute: Public__rootDefaultTermsOfUseRoute,
    Public__rootDefaultCheckoutSuccessRoute:
      Public__rootDefaultCheckoutSuccessRoute,
    Public__rootDefaultMemesMemeIdRoute: Public__rootDefaultMemesMemeIdRoute,
    Public__rootDefaultPasswordCreateNewRoute:
      Public__rootDefaultPasswordCreateNewRoute,
    Public__rootDefaultPasswordResetRoute:
      Public__rootDefaultPasswordResetRoute,
    Public__rootDefaultMemesIndexRoute: Public__rootDefaultMemesIndexRoute,
    Public__rootDefaultPricingIndexRoute: Public__rootDefaultPricingIndexRoute,
    Public__rootDefaultRandomIndexRoute: Public__rootDefaultRandomIndexRoute,
    Public__rootDefaultSubmitIndexRoute: Public__rootDefaultSubmitIndexRoute,
    Public__rootDefaultMemesCategorySlugRoute:
      Public__rootDefaultMemesCategorySlugRoute,
  }

const Public__rootDefaultRouteRouteWithChildren =
  Public__rootDefaultRouteRoute._addFileChildren(
    Public__rootDefaultRouteRouteChildren,
  )

interface Public__rootRouteRouteChildren {
  Public__rootDefaultRouteRoute: typeof Public__rootDefaultRouteRouteWithChildren
  Public__rootIndexRoute: typeof Public__rootIndexRoute
}

const Public__rootRouteRouteChildren: Public__rootRouteRouteChildren = {
  Public__rootDefaultRouteRoute: Public__rootDefaultRouteRouteWithChildren,
  Public__rootIndexRoute: Public__rootIndexRoute,
}

const Public__rootRouteRouteWithChildren =
  Public__rootRouteRoute._addFileChildren(Public__rootRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDownloaderRoute: typeof AdminDownloaderRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLibraryMemeIdRoute: typeof AdminLibraryMemeIdRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminLibraryIndexRoute: typeof AdminLibraryIndexRoute
  AdminSubmissionsIndexRoute: typeof AdminSubmissionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDownloaderRoute: AdminDownloaderRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLibraryMemeIdRoute: AdminLibraryMemeIdRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminLibraryIndexRoute: AdminLibraryIndexRoute,
  AdminSubmissionsIndexRoute: AdminSubmissionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudioRouteChildren {
  StudioMemesMemeIdStudioRoute: typeof StudioMemesMemeIdStudioRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioMemesMemeIdStudioRoute: StudioMemesMemeIdStudioRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Public__rootRouteRoute: Public__rootRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  HealthRoute: HealthRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  ReelsRoute: ReelsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapCategoriesDotxmlRoute: SitemapCategoriesDotxmlRoute,
  SitemapMemesDotxmlRoute: SitemapMemesDotxmlRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBunnyRoute: ApiBunnyRoute,
  ApiSentryTunnelRoute: ApiSentryTunnelRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronCleanupRoute: ApiCronCleanupRoute,
  ApiCronSyncAlgoliaRoute: ApiCronSyncAlgoliaRoute,
  ApiCronSyncBunnyTitlesRoute: ApiCronSyncBunnyTitlesRoute,
  ApiCronVerificationReminderRoute: ApiCronVerificationReminderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
